### ISSUE TITLE
PHP8 upgrade causes OUGC plugin errors 

### ISSUE THREAD

**Issue by Tarekma7** [OUGC-Network/OUGC-Awards#71]
After upgrade from PHP 7.4 to PHP 8 om mybb 1.8.30, the OUGC award plugin shows some errors and fatal error on ACP that prevent access to ACP

Reverting back to PHP 7.4, everything returned working with no problems 

Please update the plugin

**Comment by Sama34** [comment]
Should be fixed in Awards 1.8.33
