### ISSUE TITLE
Blank plugins page

### ISSUE THREAD

**Issue by elixir-rok** [OUGC-Network/OUGC-Awards#78]
My plugins page fully goes blank when i put the ougc_awards.php into my plugins folder

1. Install all of the plugins files
2. and go to plugins page

idk what happend but its not working

**Screenshots**
https://prnt.sc/gthIcuVa20_n

 - OS: [Windows]
 - Browser [Opera GX]
 - Version [Latest]

it just fully turns the plugins page blank and theres nothing there.

**Comment by Theanonymous05** [comment]
have the same since like a year tried it multiple times again

**Comment by elixir-rok** [comment]
found a fix downgrade to php 7.4

**Comment by Sama34** [comment]
Should be fixed in Awards 1.8.33
